### ISSUE TITLE
Instance method `success?` does not exist

### ISSUE THREAD

**Issue by igkyab** [TheMenu/command#13]
# Error description

When i use the `mock_command` method in my specs, i have an error `the xxx class does not implement the instance method: success?` which is throw.

After some research, i found the error is throw on [this line](https://github.com/TheMenu/command/blob/master/lib/command/spec_helpers/mock_command_helper.rb#L47).

I also found that the méthode `success?` is no longer present in this [file](https://github.com/TheMenu/command/blob/master/lib/command.rb).

## Versions
**Command version** : 0.0.1
**App Ruby version**: 2.7.1

**Comment by Aquaj** [comment]
This is related to the recent merge of #11. I'm taking the point so we can make the helpers work again.
